version: '3.8'

services:
  discord-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: poprikolu-discord-bot
    restart: unless-stopped
    environment:
      # Переменные окружения будут загружены из .env файла
      - NODE_ENV=production
    env_file:
      - .env
    volumes:
      # Монтируем директорию для логов
      - ./logs:/app/logs
    networks:
      - bot-network
    healthcheck:
      test: ["CMD", "node", "-e", "console.log('Bot is running')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

networks:
  bot-network:
    driver: bridge

volumes:
  bot-logs:
    driver: local